# Generated by Django 4.2.14 on 2024-08-02 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0002_rename_price_product_unit_price"),
    ]

    operations = [
        migrations.AddField(
            model_name="address",
            name="zip",
            field=models.IntegerField(default="0", max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="product",
            name="slug",
            field=models.SlugField(default="-"),
        ),
    ]
